package com.comma.learnabout.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.comma.learnabout.entity.FileInfo;
import com.comma.learnabout.entity.ThreadInfo;
import com.comma.learnabout.mutidown.DownLoadInfo;

import com.comma.learnabout.greendao.FileInfoDao;
import com.comma.learnabout.greendao.ThreadInfoDao;
import com.comma.learnabout.greendao.DownLoadInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fileInfoDaoConfig;
    private final DaoConfig threadInfoDaoConfig;
    private final DaoConfig downLoadInfoDaoConfig;

    private final FileInfoDao fileInfoDao;
    private final ThreadInfoDao threadInfoDao;
    private final DownLoadInfoDao downLoadInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fileInfoDaoConfig = daoConfigMap.get(FileInfoDao.class).clone();
        fileInfoDaoConfig.initIdentityScope(type);

        threadInfoDaoConfig = daoConfigMap.get(ThreadInfoDao.class).clone();
        threadInfoDaoConfig.initIdentityScope(type);

        downLoadInfoDaoConfig = daoConfigMap.get(DownLoadInfoDao.class).clone();
        downLoadInfoDaoConfig.initIdentityScope(type);

        fileInfoDao = new FileInfoDao(fileInfoDaoConfig, this);
        threadInfoDao = new ThreadInfoDao(threadInfoDaoConfig, this);
        downLoadInfoDao = new DownLoadInfoDao(downLoadInfoDaoConfig, this);

        registerDao(FileInfo.class, fileInfoDao);
        registerDao(ThreadInfo.class, threadInfoDao);
        registerDao(DownLoadInfo.class, downLoadInfoDao);
    }
    
    public void clear() {
        fileInfoDaoConfig.clearIdentityScope();
        threadInfoDaoConfig.clearIdentityScope();
        downLoadInfoDaoConfig.clearIdentityScope();
    }

    public FileInfoDao getFileInfoDao() {
        return fileInfoDao;
    }

    public ThreadInfoDao getThreadInfoDao() {
        return threadInfoDao;
    }

    public DownLoadInfoDao getDownLoadInfoDao() {
        return downLoadInfoDao;
    }

}
