package com.comma.learnabout.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.comma.learnabout.mutidown.DownLoadInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DOWN_LOAD_INFO".
*/
public class DownLoadInfoDao extends AbstractDao<DownLoadInfo, Long> {

    public static final String TABLENAME = "DOWN_LOAD_INFO";

    /**
     * Properties of entity DownLoadInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property DownUrl = new Property(1, String.class, "downUrl", false, "DOWNURL");
        public final static Property StartLocation = new Property(2, int.class, "startLocation", false, "STARTLOCATION");
        public final static Property EndLocation = new Property(3, int.class, "endLocation", false, "ENDLOCATION");
        public final static Property FileSize = new Property(4, int.class, "fileSize", false, "FILESIZE");
        public final static Property FinisedSize = new Property(5, int.class, "finisedSize", false, "FINISEDSIZE");
    }


    public DownLoadInfoDao(DaoConfig config) {
        super(config);
    }
    
    public DownLoadInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DOWN_LOAD_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"DOWNURL\" TEXT," + // 1: downUrl
                "\"STARTLOCATION\" INTEGER NOT NULL ," + // 2: startLocation
                "\"ENDLOCATION\" INTEGER NOT NULL ," + // 3: endLocation
                "\"FILESIZE\" INTEGER NOT NULL ," + // 4: fileSize
                "\"FINISEDSIZE\" INTEGER NOT NULL );"); // 5: finisedSize
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DOWN_LOAD_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DownLoadInfo entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String downUrl = entity.getDownUrl();
        if (downUrl != null) {
            stmt.bindString(2, downUrl);
        }
        stmt.bindLong(3, entity.getStartLocation());
        stmt.bindLong(4, entity.getEndLocation());
        stmt.bindLong(5, entity.getFileSize());
        stmt.bindLong(6, entity.getFinisedSize());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DownLoadInfo entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String downUrl = entity.getDownUrl();
        if (downUrl != null) {
            stmt.bindString(2, downUrl);
        }
        stmt.bindLong(3, entity.getStartLocation());
        stmt.bindLong(4, entity.getEndLocation());
        stmt.bindLong(5, entity.getFileSize());
        stmt.bindLong(6, entity.getFinisedSize());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public DownLoadInfo readEntity(Cursor cursor, int offset) {
        DownLoadInfo entity = new DownLoadInfo( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // downUrl
            cursor.getInt(offset + 2), // startLocation
            cursor.getInt(offset + 3), // endLocation
            cursor.getInt(offset + 4), // fileSize
            cursor.getInt(offset + 5) // finisedSize
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DownLoadInfo entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setDownUrl(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setStartLocation(cursor.getInt(offset + 2));
        entity.setEndLocation(cursor.getInt(offset + 3));
        entity.setFileSize(cursor.getInt(offset + 4));
        entity.setFinisedSize(cursor.getInt(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DownLoadInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DownLoadInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DownLoadInfo entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
